### ISSUE TITLE
Spiel nicht lauffähig

### ISSUE THREAD

**Issue by Nevs08** [GMoney597/Twitch-Spediteur#1]
Hi,

wollte das Spiel testen und bin bereits beim ersten Kompillieren auf einige Probleme gestoßen welche überarbeitet werden sollten.

1. SQLite Datenbank Datei kann nicht gefunden werden

Da in der SQLite Klasse in der Zeile 19 der Speicherort der DB Datei "Hart" aufs Laufwerk "E"  gesetzt wird müsste ich die Datei dort auch hinlegen, habe jedoch kein "E" Laufwerk. 
Lösungsvorschlag: twitch.db - Datei in den Eigenschaften "Ins Ausgabeverzeichnis kopieren - Kopieren, wenn neuer" und in der SQLite Klasse die Datei aus dem CurrentDirectory Laden.

2. Entfernungsfenster Fehler wegen fehlendem API Key

Wenn ich versuche das Entfernungsfenster auf der Startseite zu öffnen bekomme ich ebenfalls eine Fehlermeldung: "System.IO.DirectoryNotFoundException: "Could not find a part of the path 'd:\projekte\api-keys.txt'."
Eigentlich ein ähnlicher Fehler zum 1. Probleme welches sich ähnlich lösen lassen würde. Außerdem wäre es noch praktisch wenn man wüsste wie die Datei auszusehen hat.

3. twitch.db Aktuell?

DIe mitgelieferte twitch.db scheint nicht aktuell zu sein. Zum einen mal sind dort bereits 3 User Accounts angelegt (Weiß nicht ob das gewollt ist?). Zum anderen muss man nach dem Registrieren und 1. Login seinen Start-Ort wählen. Die Liste ist jedoch leer da ein Fehler ausgelöst wird: "Ausnahme ausgelöst: "System.Data.SQLite.SQLiteException" in System.Data.SQLite.dll" "SQLite error (1): no such table: t_Orte in "SELECT * FROM t_Orte""

Weiteres Testen war mir aufgrund der Fehler aktuell nicht möglich werde mich aber nochmal dran setzen wenn ein Fix da ist ;)

Desweiteren bleibt mir noch ein Tipp: Ich habe nach dem Registrieren nicht direkt verstanden wie ich mich Einloggen kann. Eventuell sollte man das noch verbessern. So hat man das gefühl dass man immer seinen Nutzernamen, E-Mail und Passwort auch zum Anmelden angeben muss.

**Comment by GMoney597** [comment]
Hi Nevs08,
danke für deine Hinweise, ich habe mal ein paar Fixes durchgeführt und erkläre diese dann im nächsten Stream.
Im Stream habe ich auch erwähnt, dass der API-Key nicht mit in GitHub übergeben wird, den muss sich jeder holen, wir sprechen da aber auch gern im Stream drüber.
Ansonsten habe ich die DB aktualisiert und diese sollte in der aktuellsten Fassung auch mit hochgeladen werden und ja, es sind ein paar Daten bei den Spielern hinterlegt, bspw. jener, die ich zum Testen aus den Viewern und Supportern genommen habe.
Wir gehen aber auf jeden Fall auf deine Issues ein - es ist wichtig, dass die Leute auch wissen, wie man in GitHubs Issues erstellt usw.

Daher vielen vielen Dank.
Die Pfade habe ich in die Ressourcen-Settings eingestellt, und so kann jeder seine Datenbank dort ablegen wo er möchte und muss diese nur in den Settings einstellen.

Bis später
Gruß
Tony
